name: Weekly Bluesky Likes Email

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  send-weekly-likes:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
      BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
      BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Fetch and send Bluesky likes
        run: npm run fetch-likes
