name: Weekly Bluesky Likes Email

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  send-weekly-likes:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
      BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
      BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Fetch and send Bluesky likes
        run: deno task fetch-likes
